config/routes.rb
# [NOTE] Some things mixed between get and post
# https://github.com/k41n/redmine_milestones/commit/fb9cb2e6b612f82d1cb70090d713c048f383291f
RedmineApp::Application.routes.draw do

  resources :projects do
    resources :milestones
  end

  resources :versions do
    resources :milestones do
      collection do
        get 'report_for_version'
      end
    end
  end

  resources :milestones do
    collection do
      get 'parent_project_changed'
      get 'subproject_changed'
      get 'recalculate_planned_end_date'
      get 'recalculate_start_date'
      get 'recalculate_actual_date'
      get 'issue_version_changed'
      get 'milestone_version_changed'
      get 'add_assigned_project'
      post 'update_settings'
    end
    member do
      post 'status_by'
      get 'report'
      get 'planned_end_date_changed'
      get 'start_date_changed'
    end
  end
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  unloadable

  before_filter :find_project, :only => [:index, :new, :create]

  def new
    @milestone = Milestone.new
    #session[:version_id] = @project.versions.first.id
  end

  def edit
    @milestone = Milestone.find(params[:id])
    @project = @milestone.project
    #session[:version_id] = @milestone.version.id if @milestone.version
  end

  def update_settings
    @project = Project.find(params[:project_id])
    @default_show_milestones = MilestonesSettings.find_by_key_and_project_id("default_show_milestones", @project.id)
    if params[:default_show_milestones]
      @default_show_milestones.update_attribute(:value, "true")
    else
      @default_show_milestones.update_attribute(:value, "false")
    end
    @default_show_closed_milestones = MilestonesSettings.find_by_key_and_project_id("default_show_closed_milestones", @project.id)
    if params[:default_show_closed_milestones]
      @default_show_closed_milestones.update_attribute(:value, "true")
    else
      @default_show_closed_milestones.update_attribute(:value, "false")
    end
    @default_show_sub_milestones = MilestonesSettings.find_by_key_and_project_id("default_show_sub_milestones", @project.id)
    if params[:default_show_sub_milestones]
      @default_show_sub_milestones.update_attribute(:value, "true")
    else
      @default_show_sub_milestones.update_attribute(:value, "false")
    end
    redirect_to :controller => 'projects', :action => 'settings', :tab => 'milestones', :id => @project
  end

  def check_visibility_lost
    @milestone = Milestone.find(params[:id])
    @old_sharing_model = @milestone.sharing
    @parents = @milestone.parents.select{|x| x.project.id != @milestone.project.id}
    @milestone.update_attribute(:sharing, params[:new_val])
    @visibility_lost = @parents.select do |x|
      not x.project.shared_milestones.map(&:id).include? @milestone.id
    end.count
    @milestone.update_attribute(:sharing, @old_sharing_model)
  end

  def update
    @milestone = Milestone.find(params[:id])
    params[:milestone][:observers] ||= []
    if params[:milestone].present? and params[:milestone][:assigned_milestones].nil?
      params[:milestone][:assigned_milestones] = []
    end
    @project = @milestone.project
    if params[:milestone]
      attributes = params[:milestone].dup
      attributes.delete('sharing') unless attributes.nil? || @milestone.allowed_sharings.include?(attributes['sharing'])
      @milestone.safe_attributes = attributes
    end
    if @milestone.save
      @milestone.break_shared_assignments
      flash[:notice] = l(:notice_successful_update)
      if params[:back_url]
        uri = URI.parse(CGI.unescape(params[:back_url].to_s))
        if /\/projects\/[^\/]+\/settings/.match uri.path
          redirect_to :controller => 'projects', :action => 'settings', :tab => 'milestones', :id => @project
        else
          redirect_back_or_default(nil)
        end
      else
        redirect_to :controller => 'projects', :action => 'settings', :tab => 'milestones', :id => @project
      end
    else
      render :action => :edit
    end
  end

  def destroy
    @milestone = Milestone.find(params[:id])
    @milestone.destroy
    if request.xhr?
    else
      if params[:back_url]
        redirect_to params[:back_url]
      else
        redirect_to settings_project_path(@milestone.project, :tab => :milestones)
      end
    end
  end

  def create
    params[:milestone][:observers] ||= []
    @milestone = Milestone.new(:project => @project)
    if params[:milestone]
      attributes = params[:milestone].dup
      attributes.delete('sharing') unless attributes.nil? || @milestone.allowed_sharings.include?(attributes['sharing'])
      @milestone.safe_attributes = attributes
    end

    if request.post?
      if @milestone.save
        flash[:notice] = l(:notice_successful_create)
        if params[:back_url]
          uri = URI.parse(CGI.unescape(params[:back_url].to_s))
          if /\/projects\/[^\/]+\/settings/.match uri.path
            redirect_to :controller => 'projects', :action => 'settings', :tab => 'milestones', :id => @project
          else
            redirect_back_or_default(nil)
          end
        else
          redirect_to :controller => 'projects', :action => 'settings', :tab => 'milestones', :id => @project
        end
      else
        respond_to do |format|
          format.html { render :action => 'new' }
        end
      end
    end
  end

  def recalculate_planned_end_date
    @reference_milestone = Milestone.find(params[:from])
    @calculated_date = @reference_milestone.planned_end_date.present? ? params[:offset].to_i.days.since(@reference_milestone.planned_end_date) : nil
  end

  def recalculate_start_date
    @reference_milestone = Milestone.find(params[:from])
    @calculated_date = @reference_milestone.start_date.present? ? params[:offset].to_i.days.since(@reference_milestone.start_date) : nil
  end

  def recalculate_actual_date
    @calculated_date = Milestone.find(params[:id]).actual_date
  end

  def parent_project_changed
    @project = Project.find(params[:id])
    session[:version] = @project.versions.first
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def subproject_changed
    @subproject = Project.find(params[:id])
    session[:version] = @subproject.versions.first
  rescue ActiveRecord::RecordNotFound
    @subproject = nil
  end

  def show
    @milestone = Milestone.find(params[:id])
    @issues = @milestone.issues
    @project = @milestone.project
  end

  def status_by
    @milestone = Milestone.find(params[:id])
    @issues = @milestone.issues
    @project = @milestone.project
    render :action => 'show'
  end

  def issue_version_changed
    @project = Project.find(params[:project_id])
    @version = Version.find(params[:id])
    @milestones = @version.milestones + @project.milestones.versionless + @project.all_milestones(false)
    @milestones.uniq
  rescue
    @milestones = @project.milestones.versionless
  end

  def milestone_version_changed
    @project = Project.find(params[:project_id])
    @version = Version.find(params[:id]) unless params[:id].to_i.zero? or params[:id].nil?
  end

  def report_for_version
    @version = Version.find(params[:version_id])
    @project = @version.project
    @data = {}
    @data["percentage"] = @version.milestones.collect{|x| x.completed_pourcent}
    @data["legend"] = @version.milestones.collect{|x| "%%.%% #{x.name}"}
    @data["href"] = @version.milestones.collect{|x| milestone_path(x)}
  end

  def report
    @milestone = Milestone.find(params[:id])
    @project = @milestone.project
    @data = {}
    @data["percentage"] = @milestone.children.collect{|x| x.completed_pourcent}
    @data["legend"] = @milestone.children.collect{|x| "%%.%% #{x.name}"}
    @data["href"] = @milestone.children.collect{|x| milestone_path(x)}
  end

  def planned_end_date_changed
    @milestone = Milestone.find(params[:id]) unless params[:id].to_i == -1
    @version = Version.find(params[:version_id])
    @newval = Date.parse(params[:newval])
    @oob_warning = I18n.t(:planned_oob_warning)
    @confirmations = ''
    if @milestone.present?
      @confirmations = @milestone.depending_from_this_start_date.collect do |milestone|
        "Milestone ##{milestone.id} #{milestone.name}, start date will be changed from #{milestone.start_date.strftime('%Y-%m-%d')} to #{milestone.start_date_offset.days.since(@newval).strftime('%Y-%m-%d')}"
      end.join("\n")
      @confirmations += "\n"+@milestone.depending_from_this_planned_end_date.reject{|x| x.planned_end_date_offset.nil?}.collect do |milestone|
        "Milestone ##{milestone.id} #{milestone.name}, planned end date will be changed from #{milestone.planned_end_date.strftime('%Y-%m-%d')} to #{milestone.planned_end_date_offset.days.since(@newval).strftime('%Y-%m-%d')}"
      end.join("\n")
    end
  end

  def start_date_changed
    @milestone = Milestone.find(params[:id]) unless params[:id].nil? or params[:id].to_i == -1
    @version = Version.find(params[:version_id])
    @newval = Date.parse(params[:newval])
    @oob_warning = I18n.t(:start_oob_warning)
  end

  def set_planned_to_actual
    @assigned_milestones = params[:assigned_milestones_ids].split("|").reject{|x| x.empty?}.map{|x| Milestone.find(x)}
    @actual = @assigned_milestones.reject{|x| x.actual_date.nil?}.max{|a,b| a.actual_date <=> b.actual_date}.actual_date unless params[:assigned_milestones_ids].nil? or params[:assigned_milestones_ids].empty?
    if params[:id] != 'undefined'
      @milestone = Milestone.find(params[:id])
      @actual = @milestone.actual_date
    end
  end

  def confirm_delete
    @milestone = Milestone.find(params[:id])
  end

  private
  def find_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end



end

app/helpers/milestones_helper.rb
module MilestonesHelper
  def format_version_sharing(sharing)
    sharing = 'none' unless Milestone::MILESTONE_SHARINGS.include?(sharing)
    l("label_milestone_sharing_#{sharing}")
  end

  STATUS_BY_CRITERIAS = %w(category tracker status priority author assigned_to)

  def render_issue_status_by(milestone, criteria)
    criteria = 'category' unless STATUS_BY_CRITERIAS.include?(criteria)

    h = Hash.new {|k,v| k[v] = [0, 0]}
    begin
      # Total issue count
      Issue.count(:group => criteria,
                  :conditions => ["#{Issue.table_name}.milestone_id = ?", milestone.id]).each {|c,s| h[c][0] = s}
      # Open issues count
      Issue.count(:group => criteria,
                  :include => :status,
                  :conditions => ["#{Issue.table_name}.milestone_id = ? AND #{IssueStatus.table_name}.is_closed = ?", milestone.id, false]).each {|c,s| h[c][1] = s}
    rescue ActiveRecord::RecordNotFound
      # When grouping by an association, Rails throws this exception if there's no result (bug)
    end
    counts = h.keys.compact.sort.collect {|k| {:group => k, :total => h[k][0], :open => h[k][1], :closed => (h[k][0] - h[k][1])}}
    max = counts.collect {|c| c[:total]}.max

    render :partial => 'issue_counts', :locals => {:milestone => milestone, :criteria => criteria, :counts => counts, :max => max}
  end

  def status_by_options_for_select(value)
    options_for_select(STATUS_BY_CRITERIAS.collect {|criteria| [l("field_#{criteria}".to_sym), criteria]}, value)
  end

  # http://railscasts.com/episodes/197-nested-model-form-part-2?view=asciicast
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f=>builder)
    end
    link_to_function(name, h("add_fields(this,\"#{association}\", \"#{escape_javascript(fields)}\")"))
  end

  def link_to_add_children_milestone_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f=>builder)
    end
    link_to_function(name, h("add_children_milestone_fields(this,\"#{association}\", \"#{escape_javascript(fields)}\")"))
  end

  def link_to_add_parent_milestone_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f=>builder)
    end
    link_to_function(name, h("add_parent_milestone_fields(this,\"#{association}\", \"#{escape_javascript(fields)}\")"))
  end

  def milestone_name_from_pov_of(project, milestone)
    if milestone.project_id == project.id
      if milestone.versionless?
        milestone.name
      else
        "#{milestone.version.name}/#{milestone.name}"
      end
    else
      if milestone.versionless?
        "#{milestone.project.name}/#{milestone.name}"
      else
        "#{milestone.project.name}/#{milestone.version.name}/#{milestone.name}"
      end

    end
  end

  def link_to_milestone(milestone, options = {})
    return '' unless milestone && milestone.is_a?(Milestone)
    link_to_if milestone.project.visible?, milestone.name, { :controller => 'milestones', :action => 'show', :id => milestone }, options
  end

  def special_calendar_for(field_id, onselect)
    content_for :header_tags do
    start_of_week = Setting.start_of_week
    start_of_week = l(:general_first_day_of_week, :default => '1') if start_of_week.blank?
    # Redmine uses 1..7 (monday..sunday) in settings and locales
    # JQuery uses 0..6 (sunday..saturday), 7 needs to be changed to 0
    start_of_week = start_of_week.to_i % 7
    tags = javascript_tag(
      "var datepickerOptions={dateFormat: 'yy-mm-dd', firstDay: #{start_of_week}, " +
      "showOn: 'button', buttonImageOnly: true, buttonImage: '" +
      path_to_image('/images/calendar.png') +
      "', showButtonPanel: true, showWeek: true, showOtherMonths: true, selectOtherMonths: true,onSelect: function(){#{onselect}}};")
    jquery_locale = l('jquery.locale', :default => current_language.to_s)
   
    unless jquery_locale == 'en'
      tags << javascript_include_tag("i18n/jquery.ui.datepicker-#{jquery_locale}.js")
    end
    tags
  end
  
  javascript_tag("$(function() { $('##{field_id}').datepicker(datepickerOptions); });")
  end

end

app/views/hooks/milestones/_view_issues_context_menu_start.html.erb
<% unless @project.nil? || @project.shared_versions.open.empty? -%>
    <% if @project.module_enabled?(:milestones_module) %>    
        <li class="folder">
          <a href="#" class="submenu"><%= l(:field_milestone) %></a>
          <ul>
            <% params[:ids].collect{|x| Issue.find(x).project.milestones}.flatten.uniq{|x| x.id}.sort.each do |milestone| -%>
		<% unless milestone.completed?  %>
                    <li><%= context_menu_link milestone.name, {:controller => 'issues', :action => 'bulk_update', :ids => @issues.collect(&:id), :issue => {'milestone_id' => milestone}, :back_url => @back}, :method => :post,
                                          :selected => (@issue && milestone == @issue.milestone), :disabled => !@can[:update] %></li>
		<% end %>
            <% end -%>
            <li><%= context_menu_link l(:label_none), {:controller => 'issues', :action => 'bulk_update', :ids => @issues.collect(&:id), :issue => {'milestone_id' => nil}, :back_url => @back}, :method => :post,
                                      :selected => (@issue && @issue.milestone.nil?), :disabled => !@can[:update] %></li>
          </ul>
        </li>
    <% end %>
<% end %>

app/views/hooks/milestones/_view_issues_form_details_bottom.html.erb
<% if @project.module_enabled?(:milestones_module) %>
    <p id="milestone_placeholder">
        <% @milestones = @project.milestones.versionless %>
        <% @milestones += @project.all_milestones(true) %>
        <% if issue.fixed_version.present? and not issue.fixed_version.milestones.empty? %>
            <% @milestones += issue.fixed_version.milestones %>
        <% end %>
        <% @milestones = @milestones.uniq %>
	<% @milestones.delete_if { |ms| ms.completed? }  %>
        <% unless @milestones.empty? %>
            <%= form.select :milestone_id, [['',0]] + @milestones.collect{|x| x.version.present? ? ["#{x.version.name}/#{x.name}", x.id] : [x.name, x.id]} %>
        <% end %>
    </p>
<% end %>
<% content_for :header_tags do %>
    <%= javascript_include_tag "milestones.js", :plugin => 'redmine_milestones' %>
    <script type="text/javascript">
        window.root_path = "<%= home_path.gsub(/\/$/,'') %>";
	$(document).ready(function() {
		$("#issue_fixed_version_id").change(function () {
			issue_version_changed("<%= @project.id  %>");
		});
        });
    </script>
<% end %>

app/views/hooks/milestones/_view_issues_show_details_bottom.html.erb
<% if issue.project.module_enabled?(:milestones_module) %>
    <% if issue.milestone.present? %>
        <th>
          <%= t(:field_milestone) %>
        </th>
        <td>
          <%= issue.milestone.name %>
        </td>
    <% end %>
<% end %>

app/views/hooks/milestones/_view_projects_roadmap_version_bottom.html.erb
<% if @project.module_enabled?(:milestones_module) %>
    <% @default_show_milestones = MilestonesSettings.find_or_create_by_project_id_and_key(@project.id, "default_show_milestones") %>
    <% @default_show_closed_milestones = MilestonesSettings.find_or_create_by_project_id_and_key(@project.id, "default_show_closed_milestones") %>
    
    <% if ((@default_show_milestones.enabled? and not params[:hide_milestones] == '1') or (@default_show_milestones.disabled? and params[:milestones])) %>
        <% if (@default_show_closed_milestones.enabled? and not params[:hide_completed_milestones] == '1') or (@default_show_closed_milestones.disabled? and params[:completed_milestones]) %>
            <%= render :partial => "milestones/milestone", :collection => Milestone.direct_children_of_version(version) %>
        <% else %>
            <%= render :partial => "milestones/milestone", :collection => Milestone.opened.direct_children_of_version(version) %>
        <% end %>
    <% end %>
<% end %>

app/views/hooks/milestones/_view_versions_show_bottom.html.erb
<% if @project.module_enabled?(:milestones_module) %>
    <% unless version.milestones.empty? %>
        <table class="list related-issues">
          <caption><%= l(:label_related_milestones) %></caption>
          <%- version.milestones.each do |milestone| -%>
              <tr class="hascontextmenu">
                <td><%= link_to_milestone(milestone) %></td>
              </tr>
          <% end %>
        </table>
    <% end %>
<% end %>


<%= context_menu issues_context_menu_path %>

app/views/hooks/milestones/_view_versions_show_contextual.html.erb
<%= link_to l(:label_reports), report_for_version_version_milestones_path(version), :class => 'icon icon-add' if User.current.allowed_to?(:manage_versions, version.project) %>