config/routes.rb
# [NOTE] Some things mixed between get and post
# https://github.com/k41n/redmine_milestones/commit/fb9cb2e6b612f82d1cb70090d713c048f383291f
RedmineApp::Application.routes.draw do

  resources :projects do
    resources :milestones
  end

  resources :versions do
    resources :milestones do
      collection do
        get 'report_for_version'
      end
    end
  end

  resources :milestones do
    collection do
      get 'parent_project_changed'
      get 'subproject_changed'
      get 'recalculate_planned_end_date'
      get 'recalculate_start_date'
      get 'recalculate_actual_date'
      get 'issue_version_changed'
      get 'milestone_version_changed'
      get 'add_assigned_project'
      post 'update_settings'
    end
    member do
      post 'status_by'
      get 'report'
      get 'planned_end_date_changed'
      get 'start_date_changed'
    end
  end
end

app/views/versions/index.html.erb
<%
   # We need that because original Redmine versions controller throws out versions without issues and don't care whether they have milestones
   @versions = @project.shared_versions || []
   @versions += @project.rolled_up_versions.visible if @with_subprojects
   @versions = @versions.uniq.sort
   unless params[:completed]
     @completed_versions = @versions.select {|version| version.closed? || version.completed? }
     @versions -= @completed_versions
   end
%>

<div class="contextual">
  <%= link_to l(:label_version_new), new_project_version_path(@project), :class => 'icon icon-add' if User.current.allowed_to?(:manage_versions, @project) %>
  <%= link_to l(:label_milestone_new), new_project_milestone_path(@project), :class => 'icon icon-add' if User.current.allowed_to?(:manage_versions, @project) and @project.module_enabled?(:milestones_module) %>
</div>

<h2><%=l(:label_roadmap)%></h2>

<% if @project.module_enabled?(:milestones_module) %>
    <% @default_show_milestones = MilestonesSettings.find_or_create_by_project_id_and_key(@project.id, "default_show_milestones") %>
    <% @default_show_closed_milestones = MilestonesSettings.find_or_create_by_project_id_and_key(@project.id, "default_show_closed_milestones") %>
    <% @milestones = @project.all_milestones(params[:with_subprojects] == '0') %>
    <% if ((@default_show_milestones.enabled? and not params[:hide_milestones] == '1') or (@default_show_milestones.disabled? and params[:milestones])) and not @milestones.select{|x| x.version.nil?}.empty? %>
        <h3>
          <%= t(:aggregate_milestones) %>
        </h3>
        <div id="roadmap">
          <% if (@default_show_closed_milestones.enabled? and not params[:hide_completed_milestones] == '1') or (@default_show_closed_milestones.disabled? and params[:completed_milestones]) %>
              <%= render :partial => "milestones/milestone", :collection => @milestones.select{|x| x.versionless? and x.orphaned?} %>
          <% else %>
              <%= render :partial => "milestones/milestone", :collection => @milestones.select{|x| x.versionless? and x.orphaned? and x.opened?} %>
          <% end %>
        </div>
    <% end %>
<% end %>    

<% @default_show_milestones = MilestonesSettings.find_or_create_by_project_id_and_key(@project.id, "default_show_milestones") %>
<% @default_show_closed_milestones = MilestonesSettings.find_or_create_by_project_id_and_key(@project.id, "default_show_closed_milestones") %>
<% @default_show_sub_milestones = MilestonesSettings.find_or_create_by_project_id_and_key(@project.id, "default_show_sub_milestones") %>

<h3><%= t(:versions) %></h3>
<% if @versions.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
    <div id="roadmap">
      <% @versions.each do |version| %>
          <h3 class="version"><%= tag 'a', :name => version.name.gsub(' ','_') %><%= link_to_version version %></h3>
          <%= render :partial => 'versions/overview', :locals => {:version => version} %>
          <%= render(:partial => "wiki/content", :locals => {:content => version.wiki_page.content}) if version.wiki_page %>
          <% @issues = @issues_by_version[version] %>
          <% @issues = @issues.uniq unless @issues.nil? %>
          <% if @project.module_enabled?(:milestones_module) %>
              <% if (@default_show_milestones.enabled? and not params[:hide_milestones] == '1') or (@default_show_milestones.disabled? and params[:milestones]) %>
                  <% unless @issues.nil? %>
                    <% @issues = @issues.select{|x| x.milestone.nil?} %>
                  <% end %>
              <% end %>
          <% end %>
          <% unless @issues.nil? or @issues.empty? %>
              <%= form_tag({}, :method => :get) do -%>
                  <table class="list related-issues">
                    <caption><%= l(:label_related_issues) %></caption>
                    <% @issues.each do |issue| -%>
                        <tr class="hascontextmenu">
                          <td class="checkbox"><%= check_box_tag 'ids[]', issue.id, false, :id => nil %></td>
                          <td><%= link_to_issue(issue, :project => (@project != issue.project)) %></td>
                        </tr>
                    <% end -%>
                  </table>
              <% end %>
          <% end %>
        <%= call_hook :view_projects_roadmap_version_bottom, :version => version %>
      <% end %>
    </div>
<% end %>


<% content_for :sidebar do %>
    <%= form_tag({}, :method => :get) do %>
        <%= hidden_field_tag :project_id, @project.id %>
        <h3><%= l(:label_roadmap) %></h3>
        <% @trackers.each do |tracker| %>
            <label><%= check_box_tag "tracker_ids[]", tracker.id, (@selected_tracker_ids.include? tracker.id.to_s), :id => nil %>
              <%=h tracker.name %></label><br />
        <% end %>
        <br />
        <label for="completed"><%= check_box_tag "completed", 1, params[:completed] %> <%= l(:label_show_completed_versions) %></label>
        <br/>
        <% if @project.module_enabled?(:milestones_module) %>        
            <% if @default_show_milestones.enabled? %>
                <label for="show_milestones"><%= check_box_tag "show_milestones", 1, params[:hide_milestones] != '1', :onclick => 'show_milestones_changed()' %> <%= l(:label_show_milestones) %></label>
                <%= hidden_field_tag "hide_milestones", params[:hide_milestones] %>
            <% else %>
                <label for="milestones"><%= check_box_tag "milestones", 1, params[:milestones] %> <%= l(:label_show_milestones) %></label>
            <% end %>
            <br/>
            <% if @default_show_closed_milestones.enabled? %>
                <label for="show_completed_milestones"><%= check_box_tag "show_completed_milestones", 1, params[:hide_completed_milestones] != '1', :onclick => 'show_hidden_milestones_changed()' %> <%= l(:label_show_completed_milestones) %></label>
                <%= hidden_field_tag "hide_completed_milestones", params[:hide_completed_milestones] %>
            <% else %>
                <label for="completed_milestones"><%= check_box_tag "completed_milestones", 1, params[:completed_milestones] %> <%= l(:label_show_completed_milestones) %></label>
            <% end %>
            <br/>
            <% if @default_show_sub_milestones.enabled? %>
                <label for="show_sub_milestones"><%= check_box_tag "show_sub_milestones", 1, params[:hide_sub_milestones] != '1', :onclick => 'show_sub_milestones_changed()' %> <%= l(:label_show_sub_milestones) %></label>
                <%= hidden_field_tag "hide_sub_milestones", params[:hide_sub_milestones] %>
            <% else %>
                <label for="show_sub_milestones"><%= check_box_tag "show_sub_milestones", 1, params[:show_sub_milestones] %> <%= l(:label_show_sub_milestones) %></label>
            <% end %>
        <% end %>
        <% if @project.descendants.active.any? %>
            <%= hidden_field_tag 'with_subprojects', 0 %>
            <br /><label><%= check_box_tag 'with_subprojects', 1, @with_subprojects %> <%=l(:label_subproject_plural)%></label>
        <% end %>
        <p><%= submit_tag l(:button_apply), :class => 'button-small', :name => nil %></p>
    <% end %>
    <% if @project.module_enabled?(:milestones_module) %>
        <% if ((@default_show_milestones.enabled? and not params[:hide_milestones] == '1') or (@default_show_milestones.disabled? and params[:milestones])) and not @project.all_milestones(params[:with_subproject] == '0').select{|x| x.version.nil?}.empty? %>
            <h3>
              <%= t(:aggregate_milestones) %>
            </h3>
            <% @milestones = @project.all_milestones(params[:with_subprojects] == '0') %>
            <% if (@default_show_closed_milestones.enabled? and not params[:hide_completed_milestones] == '1') or (@default_show_closed_milestones.disabled? and params[:completed_milestones]) %>
                <%= render :partial => "milestones/sidebar_milestone", :collection => @milestones.select{|x| x.versionless? and x.orphaned?} %>
            <% else %>
                <%= render :partial => "milestones/sidebar_milestone", :collection => @milestones.select{|x| x.versionless? and x.orphaned? and x.opened?} %>
            <% end %>
        <% end %>
    <% end %>
    <h3><%= l(:label_version_plural) %></h3>
    <% @versions.each do |version| %>
        <%= link_to format_version_name(version), "##{version.name.gsub(' ','_')}" %><br />
        <% if @project.module_enabled?(:milestones_module) %>        
            <% if ((@default_show_milestones.enabled? and not params[:hide_milestones] == '1') or (@default_show_milestones.disabled? and params[:milestones])) and not version.milestones.empty? %>
              <% if (@default_show_closed_milestones.enabled? and not params[:hide_completed_milestones] == '1') or (@default_show_closed_milestones.disabled? and params[:completed_milestones]) %>
                <%= render :partial => 'milestones/sidebar_milestone', :collection => version.milestones.orphaned, :locals => {:level => 1} %>
              <% else %>
                <%= render :partial => 'milestones/sidebar_milestone', :collection => version.milestones.opened.orphaned, :locals => {:level => 1} %>
              <% end %>
            <% end %>
        <% end %>
    <% end %>
    <% if @completed_versions.present? %>
        <p>
          <%= link_to_function l(:label_completed_versions),
	                     '   $("#toggle-completed-versions").toggleClass("collapsed"); $("#completed-versions").toggle()',
	                         :id => 'toggle-completed-versions', :class => 'collapsible collapsed' %><br />
	<span id="completed-versions" style="display:none;">
	  <%= @completed_versions.map {|version| link_to format_version_name(version), version_path(version)}.join("<br />\n").html_safe %>
	</span>
        </p>
    <% end %>
<% end %>

<div class="contextual">
  <%= link_to l(:label_version_new), new_project_version_path(@project), :class => 'icon icon-add' if User.current.allowed_to?(:manage_versions, @project) %>
  <%= link_to l(:label_milestone_new), new_project_milestone_path(@project), :class => 'icon icon-add' if User.current.allowed_to?(:manage_versions, @project) and @project.module_enabled?(:milestones_module) %>
</div>

<% html_title(l(:label_roadmap)) %>

<%= context_menu issues_context_menu_path %>

<% content_for :header_tags do %>
    <%= stylesheet_link_tag "milestones", :plugin => 'redmine_milestones' %>
    <%= javascript_include_tag "milestones", :plugin => 'redmine_milestones' %>
<% end %>
<%= context_menu issues_context_menu_path %>